#!/usr/bin/env bash
#A bash script that pings an IP address passed as an argument.

if [[ -z $1 ]];
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  for ip in "$@"
  do
    ping -c 5 "$ip";
  done
fi