#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100

iteration=1

while [ "$iteration" -le 100 ]; do
  if [ $((iteration%3)) == 0 ] && [ $((iteration%5)) == 0 ]; then
    echo "FizzBuzz"
  elif [ $((iteration%3)) == 0 ]; then
		echo "Fizz"
	elif [ $((iteration%5)) == 0 ]; then
    echo "Buzz"
	else
    echo "$iteration"
    fi
	    ((iteration++))
done
