#!/usr/bin/env bash
#Writing a bash script for 4 bad luck, 8 is your chance

iteration=1

while [ $iteration -le 10 ]; do
	if [ $iteration -eq 4 ]; then
		echo "bad luck"
	elif [ $iteration -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi:
	((iteration++))
done
