#!/usr/bin/env bash
#This bash script configures the ubuntu server, making the ff changes;
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i '/facebook\.com/d' ~/hosts.new
sed -i '1s/^/8.8.8.8 facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts